[package]
name = "glidertracker-status"
version = "0.1.0"
authors = ["Tobias Bieniek <tobias.bieniek@gmail.com>"]

[dependencies]
env_logger = "0.5.10"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ws = "0.7"
